[colors]
[colors.primary]
background = "#191f2b"
foreground = "#ffffff"

[colors.normal]
black   = "#191f2b"
red     = "#d8aead"
green   = "#e09a5c"
yellow  = "#ce8678"
blue    = "#8e8ec7"
magenta = "#c499cc"
cyan    = "#6887b6"
white   = "#d4d0d5"

[colors.bright]
black   = "#8790a3"
red     = "#f6ebeb"
green   = "#f2caa6"
yellow  = "#e9c1b9"
blue    = "#cacae7"
magenta = "#e8d5ec"
cyan    = "#a4b8d6"
white   = "#ffffff"

[colors.cursor]
text   = "#191f2b"
cursor = "#ffffff"
